services:
  backend:
    image: nikanostovan/price-tracker:latest
    container_name: price-tracker
    restart: unless-stopped
    mem_limit: 300m 
    env_file:
      - .env
    environment:
      - PROXY_URL_LIST=gluetun,gluetun2,gluetun3
      - APPLICATION_ID=${APPLICATION_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - CHANNEL_ID=${CHANNEL_ID}
      - GEO_API_KEY=${GEO_API_KEY}
      - HOME_LAT=${HOME_LAT}
      - HOME_LONG=${HOME_LONG}
    ports:
      - "6060:6060"
    depends_on:
      - gluetun
      - gluetun2
      - gluetun3
    volumes:
      - log-data:/app/logs
  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun-data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_PROTOCOL=tcp
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - FREE_ONLY=on
      - SERVER_COUNTRIES=United States
      - HTTPPROXY=on
      - UPDATER_PERIOD=12h
      - HTTPPROXY_STEALTH=on
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"none"}
  gluetun2:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=USA
      - HTTPPROXY=on
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"none"}
  gluetun3:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=USA
      - HTTPPROXY=on
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"none"}
volumes:
  log-data:
  gluetun-data:
